Implementation of multi-language support for backend
NUMde/compass-numapp-backend pull request #70
Opened 2021-12-07 12:02 UTC by alena456

2021-12-09 12:07 UTC, mahvaezi requested changes
Could you please add "language_code" to the output of the endpoint "participant" in openapi.yaml?

2021-12-13 13:46 UTC, alena456 commented on src/assets/openapi.yaml
> +    /participant/update-language-code/{subjectId}:
Hi, what do you mean by that? The api works just like "/participant/{subjectId}" and has the language code in the request body

2021-12-13 13:46 UTC, alena456 commented on db/flyway.js
> +            url: 'jdbc:postgresql://localhost:5432/compass',
I will revert.

2021-12-13 14:11 UTC, alena456 commented
> language_code

Updated in latest commit

2021-12-13 14:22 UTC, mahvaezi commented
@alena456 it would be great if the endpoint "participant" would send information about the language of the study participant. Could you still implement this change considering the time?

2021-12-13 14:26 UTC, mahvaezi commented
> > language_code
> 
> Updated in latest commit

You have to adjust the function too.

2021-12-13 15:45 UTC, alena456 commented
> language_code

Should be working now

2021-12-14 08:06 UTC, mahvaezi approved these changes

2021-12-14 09:10 UTC, alena456 commented
> Is there any specific reason why DB is not exported as default anymore?

@lenzch Can you answer that question? These changes were already present in your initial work on the multi-language change.

2021-12-14 09:27 UTC, lenzch commented
> Is there any specific reason why DB is not exported as default anymore?

@mbastian93 The export was changed to better comply with the way the exports are used in other parts of the application.

2021-12-14 13:42 UTC, mbastian93 commented
It seems like there are some lint/prettier issues and the tests also fail when run locally because the participant entry misses the `language_code`. Did you somehow deactivate the husky pre-commit hook?

2021-12-15 12:57 UTC, alena456 commented
> It seems like there are some lint/prettier issues and the tests also fail when run locally because the participant entry misses the `language_code`. Did you somehow deactivate the husky pre-commit hook?

src/types/ParticipantEntry.ts  already has language_code for Participant. It was part of this commit: https://github.com/NUMde/compass-numapp-backend/pull/70/commits/0ff88f4b59ff5a08b750ec88fdd2857cfca97ecd. Do you mean this part with "participant entry"?
No change was made for pre-commit hook from my side.

2021-12-15 13:07 UTC, mbastian93 commented
> > It seems like there are some lint/prettier issues and the tests also fail when run locally because the participant entry misses the `language_code`. Did you somehow deactivate the husky pre-commit hook?
> 
> src/types/ParticipantEntry.ts already has language_code for Participant. It was part of this commit: [0ff88f4](https://github.com/NUMde/compass-numapp-backend/commit/0ff88f4b59ff5a08b750ec88fdd2857cfca97ecd). Do you mean this part with "participant entry"? No change was made for pre-commit hook from my side.

I'm talking about the [ExampleStateModel](https://github.com/alena456/compass-numapp-backend/blob/i18n/tests/models/ExampleStateModel.test.ts).

2021-12-16 13:31 UTC, merged